export const products = [
  {
    id: 1,
    image: "/placeholder.svg",
    title: "cozy blanket",
    price: 29.99,
    category: "home decor",
    rating: 4.5,
  },
  {
    id: 2,
    image: "/placeholder.svg",
    title: "autumn mug",
    price: 12.99,
    category: "kitchen",
    rating: 4.2,
  },
  {
    id: 3,
    image: "/placeholder.svg",
    title: "fall fragrance candle",
    price: 16.99,
    category: "home decor",
    rating: 4.8,
  },
  {
    id: 4,
    image: "/placeholder.svg",
    title: "autumn leaves wall art",
    price: 39.99,
    category: "home decor",
    rating: 4.3,
  },
  {
    id: 5,
    image: "/placeholder.svg",
    title: "fall harvest wreath",
    price: 49.99,
    category: "home decor",
    rating: 4.6,
  },
  {
    id: 6,
    image: "/placeholder.svg",
    title: "spiced apple cider syrup",
    price: 12.99,
    category: "kitchen",
    rating: 4.1,
  },
  {
    id: 7,
    image: "/placeholder.svg",
    title: "fall foliage table runner",
    price: 19.99,
    category: "home decor",
    rating: 4.4,
  },
  {
    id: 8,
    image: "/placeholder.svg",
    title: "fall fashion hat",
    price: 24.99,
    category: "apparel",
    rating: 4.7,
  },
  {
    id: 9,
    image: "/placeholder.svg",
    title: "pumpkin spice latte syrup",
    price: 14.99,
    category: "kitchen",
    rating: 4.2,
  },
  {
    id: 10,
    image: "/placeholder.svg",
    title: "autumn leaves garland",
    price: 29.99,
    category: "home decor",
    rating: 4.5,
  },
  {
    id: 11,
    image: "/placeholder.svg",
    title: "cozy flannel throw blanket",
    price: 39.99,
    category: "home decor",
    rating: 4.6,
  },
  {
    id: 12,
    image: "/placeholder.svg",
    title: "pumpkin spice scented candle",
    price: 18.99,
    category: "home decor",
    rating: 4.4,
  },
];
